@startuml
|Прораб|
start
:Подготовить акт КС-2 на бумаге;
:Сфотографировать/отсканировать;
:Отправить по email в офис;
|Офис-менеджер|
:Распечатать, проверить арифметику;
:Зарегистрировать в Excel-журнале;
:Отправить сканы генподрядчику на email;
|Генподрядчик|
:Получить письмо через 2-3 дня;
:Распечатать, подписать, отсканировать;
:Вернуть по email;
|Офис-менеджер|
:Получить подписанный скан;
if (есть замечания?) then (да)
  :Перезванивать прорабу, объяснять правки;
  |Прораб|
  :Исправить вручную, снова сфотографировать;
  :Отправить заново;
  note right: Цикл может длиться 2-3 недели
else (нет)
  :Подшить в папку;
endif
|Руководитель проекта|
:Раз в месяц попросить Excel-отчёт;
:Сравнить плановые и фактические объёмы;
stop
@enduml
