@startuml
|Сотрудник|
start
:Подготовить документ;
:Отправить на согласование по email;
|Руководитель|
:Получить письмо;
:Скачать документ;
if (Есть замечания?) then (да)
  :Написать замечания в ответном письме;
  |Сотрудник|
  :Исправить документ;
  :Отправить повторно;
  |Руководитель|
else (нет)
  :Подписать (скан/файл);
endif
|Секретарь|
:Зарегистрировать в журнале;
stop
@enduml
