@startuml
|Сотрудник|
start
:Загрузить документ в систему (Confluence/CRM);
:Нажать "Отправить на согласование";
|Система|
:Автоматически уведомить руководителя;
|Руководитель|
:Открыть ссылку;
:Поставить визу/замечания онлайн;
if (Замечания?) then (да)
  |Система|
  :Уведомить сотрудника;
  |Сотрудник|
  :Исправить и отправить повторно;
  |Руководитель|
else (нет)
  |Система|
  :Зафиксировать согласование;
  :Отправить в архив;
endif
|Сотрудник|
:Получить уведомление о готовности;
stop
@enduml
